#!/bin/tcsh 
#PBS -l size=2048
#PBS -l walltime=60:00
#PBS -A 7101/16.12
#PBS -o rs2048-co2.o -e rs2048-co2.e
#PBS -N bench-dns
#PBS -q standard
#XXXB -wa URG -wt 10
#
#
#  run this script as an execuatable (do not qsub)
#  it will compile the code and then qsub itself
#
# put datestape in .o and .e file:
set datestamp = `date`
sh -c 'echo ".e output test" 1>&2'
sh -c "echo '$datestamp' 1>&2"
echo $datestamp

#
#  2048^3  = 1.2 TB
#  512 cpus:  2.4GB per process
#  1024 cpus:  1.2GB per process (wont run VN, will run CO)
#
set name = sc2048A
set refin=$HOME/dns/src/forcing12-bench.inp

set recompile = 1
set code = dnsp
set opt = "-mio -t"
set SRC=$HOME/dns/src
set WDIR=/scratch1/mataylo
mkdir $WDIR
set EXE=$HOME/$name-$$

#
#   CO or VN mode?
#
set VN=0
if ( $VN == 1) then
   set MPIRUN = "yod -VN -sz"
else
   set MPIRUN = "yod -sz"
endif





# set NCPU = 2048
# set mesh = "2 1 1024 2048 2048 2048"
# cd $SRC
# rm -f $EXE ; rm -f $code 
# ./gridsetup.py $mesh 2 2 0 ; make $code ; \cp -f $code $EXE
# $MPIRUN $NCPU $EXE $opt  -d $WDIR  $name < $refin


# set NCPU = 2048
# set mesh = "4 1 512 2048 2048 2048"
# cd $SRC
# rm -f $EXE ; rm -f $code 
# ./gridsetup.py $mesh 2 2 0 ; make $code ; \cp -f $code $EXE
# $MPIRUN $NCPU $EXE $opt  -d $WDIR  $name < $refin

# set NCPU = 2048
# set mesh = "8 1 256 2048 2048 2048"
# cd $SRC
# rm -f $EXE ; rm -f $code 
# ./gridsetup.py $mesh 2 2 0 ; make $code ; \cp -f $code $EXE
# $MPIRUN $NCPU $EXE $opt  -d $WDIR  $name < $refin

# set NCPU = 2048
# set mesh = "16 1 128 2048 2048 2048"
# cd $SRC
# rm -f $EXE ; rm -f $code 
# ./gridsetup.py $mesh 2 2 0 ; make $code ; \cp -f $code $EXE
# $MPIRUN $NCPU $EXE $opt  -d $WDIR  $name < $refin

# set NCPU = 2048
# set mesh = "32 1 64 2048 2048 2048"
# cd $SRC
# rm -f $EXE ; rm -f $code 
# ./gridsetup.py $mesh 2 2 0 ; make $code ; \cp -f $code $EXE
# $MPIRUN $NCPU $EXE $opt  -d $WDIR  $name < $refin

#didn't run CO mode: MPICH_UNEX_BUFFER_SIZE  60M
#does run eith 180M
setenv MPICH_UNEX_BUFFER_SIZE 180M
set NCPU = 1024
set mesh = "1 1 1024 2048 2048 2048"
cd $SRC
rm -f $EXE ; rm -f $code 
./gridsetup.py $mesh 2 2 0 ; make $code ; \cp -f $code $EXE
$MPIRUN $NCPU $EXE $opt  -d $WDIR  $name < $refin













